project:
  type: website
  output-dir: docs
  
website:
  title: "Daniela Palleschi"
  sidebar:
    title: "R Workflow"
    style: "docked"
    search: true
    downloads: revealjs
    contents:
      - index.qmd
      - section: "Basics"
        contents:
          # - troubleshooting.qmd
          - quarto.qmd
          - packages.qmd
          - updateR_install_packages.qmd
          - data_dictionary.qmd
          - zotero.qmd
      - section: "Next level"
        contents:
          - git.qmd
          - docker.qmd
          - gh-pages-quarto.qmd
  navbar:
    right:
      - icon: home
        href: https://daniela-palleschi.github.io/
        text: D. Palleschi
    tools:
      - icon: twitter
        href: https://twitter.com/dpalleswho
      - href: https://daniela-palleschi.github.io
        text: D. Palleschi
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/daniela-palleschi/workflow/
            
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-tools: true
    css: styles.css
    toc: true
    number-sections: true
    include-after-body: custom.html
    page-layout: full
    self-contained: true
    execute:
      message: false
      warning: false
      echo: false


bibliography: references.bib

crossref:
  exm-prefix: ex.   # (default is "Figure")
  # labels: alpha a        # (default is arabic)
  # subref-labels: alpha t # (default is alpha a)




