project:
  type: website
  output-dir: docs
  
website:
  title: "R Workflow"
  sidebar:
    style: "docked"
    search: true
    downloads: revealjs
    contents:
      - index.qmd
      - section: "Basics"
        contents:
          - troubleshooting.qmd
          - quarto.qmd
          - packages.qmd
          - updateR_install_packages.qmd
          - zotero.qmd
      - section: "Next level"
        contents:
          - git.qmd
          - docker.qmd
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/dpalleswho
      - href: https://daniela-palleschi.github.io
        text: D. Palleschi
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/daniela-palleschi/daniela-palleschi.github.io/
            
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-tools: true
    css: styles.css
    toc: true
    number-sections: true
    include-after-body: custom.html
    page-layout: full
    self-contained: true
    execute:
      message: false
      warning: false
      echo: false
  revealjs: 
    include-after-body: custom.html
    theme: [dark]
    width: 1600
    height: 900
    progress: true
    # smaller: true
    scrollable: true
    slide-number: c/t
    code-link: true
    code-overflow: wrap
    code-tools: true
    # logo: logos/hu_logo.png
    # css: logo.css
    incremental: true
    number-depth: 1
    toc: false
    toc-depth: 1
    toc-title: 'Überblick'
    navigation-mode: linear
    controls-layout: bottom-right
    fig-cap-location: top
    font-size: 0.6em
    slide-level: 4
    self-contained: true
    # chalkboard: true
    title-slide-attributes: 
      data-background-image: logos/logos.tif
      data-background-size: 15%
      data-background-position: 50% 92%
    execute:
      fig-width: 6
      fig-asp: .618
      fig-align: centre

bibliography: references.bib

crossref:
  exm-prefix: ex.   # (default is "Figure")
  # labels: alpha a        # (default is arabic)
  # subref-labels: alpha t # (default is alpha a)




